### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by RokiaAbdeen** [hi-zhengcheng/sctn#1]
thank you so much for sharing your great project !
could you please explain how to save the predicted flow and visualize it with the first and second point cloud as shown in your paper

thank you in advance

**Comment by hi-zhengcheng** [comment]
Thanks for your interest in our work. 

To save the predicted flow, the first and second point clouds, you can simply save the predicted flow(`pred_flow`) together with pc1 and pc2 using `numpy.savez`. When visualizing them, you can use `bumpy.load` to load the saved `.npz` file.

For the visualization, we first warp the first point cloud by adding `pc1` and `pred_flow`: pc1’ = pc1 + pred_flow. Then we use the library **open3d** to visualize both `pc1’` and `pc2`.

**Comment by RokiaAbdeen** [comment]
Thank you so much for your response! 
I'll try and come here back if I faced any error 

thank you
