### ISSUE TITLE
About interpolation method 

### ISSUE THREAD

**Issue by houyongkuo** [hi-zhengcheng/sctn#2]
Hello, thank you for your innovative work.
I have a question: Is the interpolation method from voxel feature to point feature in VIFE module the nearest neighbor interpolation method in the upsample function? Thanks.

**Comment by hi-zhengcheng** [comment]
Thank you for your interest in our work. Yes, you are right. The interpolation method from the voxel feature to the point feature in the `VIFE` module is the nearest neighbor interpolation method in the `upsample` function. The `upsample` method handles the job of feature interpolation: from the voxel feature to the point feature.

**Comment by houyongkuo** [comment]
Thanks for your answer. Also, I have an another question: how to draw the point cloud feature map(like Figure 1 in the paper ) ? Thanks.

**Comment by houyongkuo** [comment]
I also encountered a problem recently. If the number of point clouds is too dense or too many, the GPU memory often consumed when calculating the per-point square distance is very large. Using a 24G GPU GPU memory is not enough. How do you solve this? Thanks.

**Comment by hi-zhengcheng** [comment]
@HOUYONGKUO thanks for your questions.

For the feature map visualization, you can use t-SNE or PCA to get color for each point according to the point's feature, then visualize it using open3d or Mayavi.

For the training step, 32G GPU memory (V100) for the dense point clouds is preferred in my experience.
