### ISSUE TITLE
train on kitti

### ISSUE THREAD

**Issue by skyqwe123** [hi-zhengcheng/sctn#3]
@hi-zhengcheng @bing-li-ai 
Thanks for your project.
I want to know what do I need to change if  I train on Kitti?
eg. python train.py --nb_iter 1 --dataset HPLFlowNet --nb_points 8192 --batch_size 4 --nb_epochs 10

**Comment by hi-zhengcheng** [comment]
@skyqwe123 Thanks for your question. As you can see from the code here: 
https://github.com/hi-zhengcheng/sctn/blob/f3a9c061c819695c20359ad2aafefd542d675071/train.py#L182

the training code only supports the FlyingThings3D dataset in the current implementation. 

But if you want to train on Kitti, you can modify the dataset initialization logic in the about code to use the Kitti dataset. The Kitti dataset has already been implemented for test and validation purposes before, and you can use it for training directly.
